version: 2.1

orbs:
  python: circleci/python@0.2.1


references:
  pip_install: &pip_install
    run:
      command: |
        sudo pip install pipenv
        pipenv install
  pycache_restore: &pycache_restore
    restore_cache:
      key: deps-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
  pycache_save: &pycache_save
    save_cache:
      key: deps-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      paths:
        - ".venv"
        - "/usr/local/bin"
        - "/usr/local/lib/python3.7/site-packages"

jobs:
  run-tests:
    working_directory: ~/repo
      executor: python
      steps:
        - checkout
        - *pycache_restore
        - *pip_install
        - *pycache_save
        - run:
            command: python -m pytest

workflows:
  main:
    jobs:
      - run-tests