version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.7.3-node


references:
  pip_install: &pip_install
    run:
      command: |
        sudo pip install pipenv
        pipenv install

jobs:
  run-tests:
      working_directory: ~/repo
      executor: python
      steps:
        - checkout
        - *pip_install
        - run:
            command: echo "[Start] Run Tests"
        - run:
            command: pipenv run pytest
        - run:
            command: echo "[End] Run Tests"

workflows:
  main:
    jobs:
      - run-tests